/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BildirimlerRouteImport } from './routes/bildirimler'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as RandevularRouteImport } from './routes/randevular'
import { Route as TakvimRouteImport } from './routes/takvim'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BildirimlerRoute = BildirimlerRouteImport.update({
  id: '/bildirimler',
  path: '/bildirimler',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const RandevularRoute = RandevularRouteImport.update({
  id: '/randevular',
  path: '/randevular',
  getParentRoute: () => rootRouteImport,
} as any)
const TakvimRoute = TakvimRouteImport.update({
  id: '/takvim',
  path: '/takvim',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bildirimler': typeof BildirimlerRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/randevular': typeof RandevularRoute
  '/takvim': typeof TakvimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bildirimler': typeof BildirimlerRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/randevular': typeof RandevularRoute
  '/takvim': typeof TakvimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bildirimler': typeof BildirimlerRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/randevular': typeof RandevularRoute
  '/takvim': typeof TakvimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/bildirimler' | '/login' | '/profil' | '/randevular' | '/takvim'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bildirimler' | '/login' | '/profil' | '/randevular' | '/takvim'
  id:
    | '__root__'
    | '/'
    | '/bildirimler'
    | '/login'
    | '/profil'
    | '/randevular'
    | '/takvim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BildirimlerRoute: typeof BildirimlerRoute
  LoginRoute: typeof LoginRoute
  ProfilRoute: typeof ProfilRoute
  RandevularRoute: typeof RandevularRoute
  TakvimRoute: typeof TakvimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bildirimler': {
      id: '/bildirimler'
      path: '/bildirimler'
      fullPath: '/bildirimler'
      preLoaderRoute: typeof BildirimlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/randevular': {
      id: '/randevular'
      path: '/randevular'
      fullPath: '/randevular'
      preLoaderRoute: typeof RandevularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takvim': {
      id: '/takvim'
      path: '/takvim'
      fullPath: '/takvim'
      preLoaderRoute: typeof TakvimRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BildirimlerRoute: BildirimlerRoute,
  LoginRoute: LoginRoute,
  ProfilRoute: ProfilRoute,
  RandevularRoute: RandevularRoute,
  TakvimRoute: TakvimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
